# Generated by Django 4.2.5 on 2023-10-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='autor',
        ),
    ]
