# Generated by Django 4.2.5 on 2023-10-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_user_avatar_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='autor',
            new_name='user',
        ),
    ]
